// =============================================================
//  Madsen Properties — App Logic
//  Do not edit this file. To update listings, edit listings.js.
// =============================================================

let activeFilter = 'all';
let activeSort   = 'default';
const imgIdx     = {};

function badgeClass(s) {
  return s === 'available' ? 'badge-now' : s === 'soon' ? 'badge-soon' : 'badge-approved';
}
function bedLabel(b) {
  return b === 0 ? 'Studio' : b + ' Bed' + (b > 1 ? 's' : '');
}

/* ── Render one listing card ── */
function renderCard(l) {
  const imgs  = l.images;
  const total = imgs.length;
  imgIdx[l.id] = 0;

  const thumbs = imgs.map((src, i) =>
    `<img class="card-thumb${i === 0 ? ' active' : ''}" src="${src}" alt="" loading="lazy"
      onerror="this.style.display='none'"
      onclick="setCardImg(${l.id}, ${i})" />`
  ).join('');

  return `
  <article class="rental-card fade-in" data-id="${l.id}" data-tag="${l.tag}" data-status="${l.status}">
    <div class="card-imgs">
      <a href="listing.html?id=${l.id}" style="display:block;height:230px;overflow:hidden;">
        <img class="card-img-main" id="cimg-${l.id}"
          src="${imgs[0]}" alt="${l.address}" loading="lazy"
          onerror="this.onerror=null;this.style.opacity='.3'" />
      </a>
      <span class="card-status-badge ${badgeClass(l.status)}">${l.statusLabel}</span>
      ${total > 1 ? `
        <div class="card-img-arrows">
          <button class="card-img-arrow" onclick="cardImgNav(event,${l.id},-1)" aria-label="Previous photo">&#8249;</button>
          <button class="card-img-arrow" onclick="cardImgNav(event,${l.id}, 1)" aria-label="Next photo">&#8250;</button>
        </div>
        <span class="card-img-count" id="ccount-${l.id}">1 / ${total}</span>
        <div class="card-thumbs">${thumbs}</div>
      ` : ''}
    </div>
    <div class="card-info">
      <a href="listing.html?id=${l.id}" style="text-decoration:none;">
        <div class="card-address" style="color:#333;">${l.address}</div>
      </a>
      <div class="card-city">${l.city}</div>
      <div class="card-price">${l.price} <span>per month</span></div>
      <div class="card-meta">
        <span class="card-meta-item">🛏 ${bedLabel(l.beds)}</span>
        <span class="card-meta-item">🚿 ${l.baths} Bath</span>
        ${l.yearBuilt ? `<span class="card-meta-item">🏗 Built ${l.yearBuilt}</span>` : ''}
      </div>
      <div class="card-desc">${l.desc}</div>
      <div class="card-footer-row">
        <div class="card-avail">Available: <strong>${l.available}</strong></div>
        <div class="card-actions">
          <a href="listing.html?id=${l.id}" class="btn-outline">View Details</a>
          <a href="apply.html" class="btn-apply">Apply Now</a>
        </div>
      </div>
    </div>
  </article>`;
}

/* ── Card image navigation ── */
function setCardImg(id, idx) {
  const l = listings.find(x => x.id === id);
  if (!l) return;
  const imgs = l.images;
  imgIdx[id] = idx;
  const mainImg = document.getElementById('cimg-' + id);
  const counter = document.getElementById('ccount-' + id);
  if (mainImg) mainImg.src = imgs[idx];
  if (counter)  counter.textContent = (idx + 1) + ' / ' + imgs.length;
  const card = document.querySelector(`[data-id="${id}"]`);
  if (card) card.querySelectorAll('.card-thumb').forEach((t, i) => t.classList.toggle('active', i === idx));
}

function cardImgNav(e, id, dir) {
  e.stopPropagation();
  const l = listings.find(x => x.id === id);
  if (!l) return;
  setCardImg(id, (imgIdx[id] + dir + l.images.length) % l.images.length);
}

/* ── Filter / sort / search ── */
function applyFilters() {
  const query = document.getElementById('searchInput').value.toLowerCase().trim();
  activeSort  = document.getElementById('sortSelect').value;

  let filtered = listings.filter(l => {
    const matchFilter =
      activeFilter === 'all'       ? true :
      activeFilter === 'available' ? l.status === 'available' :
      activeFilter === 'soon'      ? l.status === 'soon' :
      l.tag === activeFilter;
    const matchSearch = !query ||
      l.address.toLowerCase().includes(query) ||
      l.city.toLowerCase().includes(query);
    return matchFilter && matchSearch;
  });

  if (activeSort === 'price-asc')  filtered.sort((a, b) => a.priceNum - b.priceNum);
  if (activeSort === 'price-desc') filtered.sort((a, b) => b.priceNum - a.priceNum);
  if (activeSort === 'avail')      filtered.sort((a, b) => a.availDate.localeCompare(b.availDate));

  document.getElementById('resultsCount').textContent =
    filtered.length + ' listing' + (filtered.length !== 1 ? 's' : '');

  document.getElementById('listingsContainer').innerHTML = filtered.length
    ? filtered.map(renderCard).join('')
    : `<div class="no-results">No listings match your search.
         <button onclick="resetFilters()">Clear filters</button>
       </div>`;
}

function setFilter(type, btn) {
  activeFilter = type;
  document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
  btn.classList.add('active');
  applyFilters();
}

function resetFilters() {
  activeFilter = 'all';
  document.getElementById('searchInput').value = '';
  document.getElementById('sortSelect').value  = 'default';
  document.querySelectorAll('.filter-btn').forEach((b, i) => b.classList.toggle('active', i === 0));
  applyFilters();
}

/* ── Lightbox ── */
let lbId = null, lbI = 0;

function openLb(id, idx) {
  lbId = id; lbI = idx; updateLb();
  document.getElementById('lightbox').classList.add('open');
  document.body.style.overflow = 'hidden';
}
function closeLb() {
  document.getElementById('lightbox').classList.remove('open');
  document.body.style.overflow = '';
}
function lbNav(dir) {
  const l = listings.find(x => x.id === lbId);
  if (!l) return;
  lbI = (lbI + dir + l.images.length) % l.images.length;
  updateLb();
}
function updateLb() {
  const l = listings.find(x => x.id === lbId);
  if (!l) return;
  document.getElementById('lbImg').src     = l.images[lbI];
  document.getElementById('lbAddress').textContent = l.address + ' — ' + l.city;
  document.getElementById('lbCounter').textContent = (lbI + 1) + ' / ' + l.images.length;
}

document.getElementById('lightbox').addEventListener('click', e => {
  if (e.target === document.getElementById('lightbox')) closeLb();
});
document.addEventListener('keydown', e => {
  if (!document.getElementById('lightbox').classList.contains('open')) return;
  if (e.key === 'ArrowLeft')  lbNav(-1);
  if (e.key === 'ArrowRight') lbNav(1);
  if (e.key === 'Escape')     closeLb();
});

/* ── Hamburger ── */
const hamburger = document.getElementById('hamburger');
const navList   = document.getElementById('navList');
hamburger.addEventListener('click', () => {
  const open = navList.classList.toggle('open');
  hamburger.classList.toggle('open', open);
  hamburger.setAttribute('aria-expanded', String(open));
});
document.addEventListener('click', e => {
  if (!hamburger.contains(e.target) && !navList.contains(e.target)) {
    navList.classList.remove('open');
    hamburger.classList.remove('open');
    hamburger.setAttribute('aria-expanded', 'false');
  }
});

/* ── Back to top ── */
const btt = document.getElementById('backToTop');
window.addEventListener('scroll', () => btt.classList.toggle('visible', window.scrollY > 400));

/* ── Contact form ── */
document.getElementById('contactForm').addEventListener('submit', async function(e) {
  e.preventDefault();
  const form = this;
  const data = new FormData(form);
  try {
    await fetch('/', { method: 'POST', headers: {'Content-Type': 'application/x-www-form-urlencoded'}, body: new URLSearchParams(data).toString() });
    document.getElementById('formSuccess').style.display = 'block';
    form.reset();
  } catch(err) {
    alert('Sorry, there was an error sending your message. Please call us at (530) 570-6192.');
  }
});

/* ── Init ── */
applyFilters();
